/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hhj73_tess4_Tesseract4 */

#ifndef _Included_com_hhj73_tess4_Tesseract4
#define _Included_com_hhj73_tess4_Tesseract4
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
