/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "../../../../../../../../Users/hhj73/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_hhj73_ocrtest_MainActivity */

#ifndef _Included_com_hhj73_ocrtest_MainActivity
#define _Included_com_hhj73_ocrtest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hhj73_ocrtest_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hhj73_ocrtest_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
extern "C"
JNIEXPORT void JNICALL
Java_com_hhj73_ocrtest_MainActivity_grayScale(JNIEnv *env, jobject instance, jlong inputImage,
                                              jlong outputImage) {

    // TODO
    Mat &inputMat = *(Mat *) inputImage;
    Mat &outputMat = *(Mat *) outputImage;

    cvtColor(inputMat, outputMat, COLOR_RGB2GRAY);

}extern "C"
JNIEXPORT void JNICALL
Java_com_hhj73_ocrtest_MainActivity_binarization__JJ(JNIEnv *env, jobject instance,
                                                     jlong inputImage, jlong outputImage) {

    // TODO

}